export type Metadata = {
    id: string,
    title: string,
    description: string,
    sourceId: string,
    sourceName: string,
};

// Request/response shapes are generated by Roma into ./roma.d.ts
// (`php artisan roma:typescript`). The types below describe Eloquent models
// passed as Inertia page props, which Roma does not own.

export type PlatformType = {
    name: string;
};

export type ClipProcessingState = {
    name: 'Processing' | 'Processed' | 'Unavailable' | 'Failed';
};

export type AudioSource = {
    name: string,
    platform_type: PlatformType,
};

export type AudioClip = {
    id: number,
    title: string,
    processing_state: ClipProcessingState,
    audio_source: AudioSource,
    platform_url: string,
    audio_url: string,
    preview_url: string | null,
    created_at: string,
    published_at: string,

}

export type Feed = {
    id: number,
    uuid: string,
    name: string,
    description: string,
    audio_clips: AudioClip[],
    subscription: AudioSource|null,
}
