<?php

namespace App\Proxies;

use App\Proxies\Contracts\ResidentialProxyConfig;
use Illuminate\Contracts\Config\Repository;
use Illuminate\Support\Str;
use RuntimeException;

/**
 * DataImpulse's residential pool, an alternative to Oxylabs. The reason for wanting a residential address at all is
 * the same one: YouTube treats an address belonging to a cable company as a person and an address belonging to a
 * hosting company as a robot, and every commercial VPN is the latter.
 *
 * DataImpulse offers two ways to hold one address. One is a range of per-port proxies, where the port decides the
 * address and the address changes on the provider's own schedule rather than ours. The other, used here, is the
 * rotating gateway on port 823 with a session parameter: we name a session, and requests carrying that name come out
 * of the same address. Only the second gives us what ProxyConfig::getUrlForDownload() asks for, which is one address
 * for the length of a download and a different one next time.
 *
 * @see https://docs.dataimpulse.com/proxies/parameters/session-id
 * @see https://docs.dataimpulse.com/proxies/parameters/session-interval
 */
class DataImpulseResidentialProxyConfig implements ResidentialProxyConfig
{
    private const string HOST = 'gw.dataimpulse.com';

    /**
     * The HTTP/HTTPS gateway that takes its parameters from the username. Port 824 is the same thing over SOCKS5, and
     * ports 10000-20000 are the per-port sticky proxies we're deliberately not using.
     */
    private const int PORT = 823;

    /**
     * How long DataImpulse should hold an address, in minutes.
     *
     * DataImpulse documents `sessttl` only for their per-port proxies and doesn't say whether port 823 honours it
     * alongside `sessid`, so we measured it. On 2026-09-18, against a real account and a URL built by this class, a
     * session was polled through the proxy every five minutes: it returned the same exit address from the first
     * request through the 55-minute poll, then a different address at 60 minutes, which it kept from there. So port
     * 823 does honour `sessttl` together with `sessid`, and the 30 minutes in their documentation is a default
     * rather than a ceiling. That run says nothing about an idle session, which was never idle for more than five
     * minutes, but a download is never idle either.
     *
     * An hour is generous on purpose: holding an address for longer than a download needs costs nothing, while an
     * address that changes midway through a download fails as an unexplained 403.
     */
    private const int SESSION_MINUTES = 60;

    public function __construct(private readonly Repository $config) {}

    public function isConfigured(): bool
    {
        return ! is_null($this->credentials());
    }

    public function getUrlForDownload(): string
    {
        $credentials = $this->credentials();

        // Callers are meant to check isConfigured() first. Say so plainly rather than letting a null credential turn
        // into a TypeError halfway through building the username, which reads like a bug in this class.
        if (is_null($credentials)) {
            throw new RuntimeException(
                'No DataImpulse credentials are configured; set DATAIMPULSE_USERNAME and DATAIMPULSE_PASSWORD to use '
                .'the residential proxy.'
            );
        }

        [$user, $password] = $credentials;

        /** @var array<string, string|int> $parameters */
        $parameters = [];

        // Downloads are refused outright from some countries, and an address near the content is faster. An install
        // that hasn't named a country gets no `cr` at all rather than an empty one, which DataImpulse reads as a
        // malformed parameter; without it they pick the exit country themselves.
        $country = $this->countryCode();

        if (! is_null($country)) {
            $parameters['cr'] = $country;
        }

        // A fresh session per call, which is per download attempt: one address for this download, a different one for
        // the next.
        $parameters['sessid'] = Str::random(16);

        $parameters['sessttl'] = self::SESSION_MINUTES;

        // DataImpulse takes its parameters in the username, not the URL's query string: the login, then a double
        // underscore, then key.value pairs joined by semicolons.
        $username = $user.'__'.collect($parameters)
            ->map(fn (string|int $value, string $key) => "$key.$value")
            ->join(';');

        // Both halves are percent-encoded. The password is generated by DataImpulse and routinely contains characters
        // that mean something else inside a URL, and the semicolons separating the parameters become %3B, which is
        // what we want: the client decodes the username before sending it.
        return sprintf(
            'http://%s:%s@%s:%d',
            rawurlencode($username),
            rawurlencode($password),
            self::HOST,
            self::PORT,
        );
    }

    /**
     * The country to take an exit address in, or null if this install hasn't named one.
     *
     * A missing or blank country means the `cr` parameter is left out of the username altogether, and DataImpulse
     * applies its own default targeting. Sending `cr.` with nothing after it would be worse than sending nothing:
     * it's a parameter with no value, which they answer with a refusal rather than a sensible default.
     *
     * Every country code in DataImpulse's documentation is lowercase, so send one whichever way the config writes it.
     */
    private function countryCode(): ?string
    {
        $country = $this->config->get('services.dataimpulse.residential.country');

        if (! is_string($country) || trim($country) === '') {
            return null;
        }

        return Str::lower(trim($country));
    }

    /**
     * The configured user and password, or null if this install hasn't got a DataImpulse account.
     *
     * Both halves are needed, and a blank one is as good as a missing one — "DATAIMPULSE_USERNAME=" with nothing
     * after it is what a .env copied from the example actually looks like, and is likelier than the key being absent.
     *
     * @return array{string, string}|null
     */
    private function credentials(): ?array
    {
        $user = $this->config->get('services.dataimpulse.residential.user');
        $password = $this->config->get('services.dataimpulse.residential.password');

        if (! is_string($user) || ! is_string($password)) {
            return null;
        }

        if (trim($user) === '' || trim($password) === '') {
            return null;
        }

        return [$user, $password];
    }

    public function requiresInsecureTls(): bool
    {
        // DataImpulse tunnels with CONNECT, so TLS stays end-to-end between us and YouTube and we can still verify it.
        return false;
    }
}
