<?php

namespace App\Proxies;

use App\Proxies\Contracts\ResidentialProxyConfig;
use Illuminate\Contracts\Config\Repository;
use Illuminate\Support\Str;

/**
 * Oxylabs' residential pool, which routes requests through other people's home connections. That's the point: YouTube
 * treats an address belonging to a cable company as a person and an address belonging to a hosting company as a robot,
 * and every commercial VPN is the latter.
 *
 * Reaching the pool at its plain address gives a different exit IP on every single request, which reads like exactly
 * what you'd want and is in fact unusable here — see ProxyConfig::getUrlForDownload(). The session parameters below
 * are what pin one address to one download.
 *
 * @see https://developers.oxylabs.io/products/proxies/residential-proxies/session-control
 */
class OxylabsResidentialProxyConfig implements ResidentialProxyConfig
{
    private const string HOST = 'pr.oxylabs.io';

    private const int PORT = 7777;

    /**
     * How long Oxylabs should hold an address, in minutes. Their default is 10, and the maximum is 1440. A lecture is
     * around 96MB and takes well under a minute at the throughput we've measured, so this is generous on purpose: the
     * cost of it being too high is nothing, and the cost of it being too low is an address that changes midway through
     * a download, which fails as an unexplained 403.
     */
    private const int SESSION_MINUTES = 60;

    public function __construct(private readonly Repository $config) {}

    public function getUrlForDownload(): string
    {
        // Oxylabs takes its parameters in the username, not the URL's query string.
        $username = collect([
            'customer' => $this->config->get('services.oxylabs.residential.user'),

            // Downloads are refused outright from some countries, and an address near the content is faster.
            'cc'       => $this->config->get('services.oxylabs.residential.country'),

            // A fresh session per call, which is per download attempt: one address for this download, a different one
            // for the next.
            'sessid'   => Str::random(16),

            'sesstime' => self::SESSION_MINUTES,
        ])
            ->map(fn (string|int $value, string $key) => "$key-$value")
            ->join('-');

        $password = $this->config->get('services.oxylabs.residential.password');

        // Both halves are percent-encoded: the password is generated by Oxylabs and routinely contains characters
        // that mean something else inside a URL.
        return sprintf(
            'http://%s:%s@%s:%d',
            rawurlencode($username),
            rawurlencode($password),
            self::HOST,
            self::PORT,
        );
    }

    public function requiresInsecureTls(): bool
    {
        // Oxylabs tunnels with CONNECT, so TLS stays end-to-end between us and YouTube and we can still verify it.
        return false;
    }
}
